
services:
  postgres:
    image: postgres:latest
    container_name: postgres_dbt_container
    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ../../data/postgres-docker-data:/var/lib/postgresql/data
      - /Users/jpk/Projects/udemy-learning-dbt/data/airbnb-data:/mnt/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
