CREATE TABLE "bronze.listings" (
	id VARCHAR NOT NULL, 
	listing_url VARCHAR NOT NULL, 
	scrape_id VARCHAR NOT NULL, 
	last_scraped VARCHAR NOT NULL, 
	source VARCHAR NOT NULL, 
	name VARCHAR NOT NULL, 
	description VARCHAR, 
	neighborhood_overview VARCHAR, 
	picture_url VARCHAR NOT NULL, 
	host_id VARCHAR NOT NULL, 
	host_url VARCHAR NOT NULL, 
	host_name VARCHAR, 
	host_since VARCHAR, 
	host_location VARCHAR, 
	host_about VARCHAR, 
	host_response_time VARCHAR, 
	host_response_rate VARCHAR, 
	host_acceptance_rate VARCHAR, 
	host_is_superhost VARCHAR, 
	host_thumbnail_url VARCHAR, 
	host_picture_url VARCHAR, 
	host_neighbourhood VARCHAR, 
	host_listings_count VARCHAR, 
	host_total_listings_count VARCHAR, 
	host_verifications VARCHAR, 
	host_has_profile_pic VARCHAR, 
	host_identity_verified VARCHAR, 
	neighbourhood VARCHAR, 
	neighbourhood_cleansed VARCHAR NOT NULL, 
	neighbourhood_group_cleansed VARCHAR NOT NULL, 
	latitude VARCHAR NOT NULL, 
	longitude VARCHAR NOT NULL, 
	property_type VARCHAR NOT NULL, 
	room_type VARCHAR NOT NULL, 
	accommoVARCHARs VARCHAR NOT NULL, 
	bathrooms VARCHAR, 
	bathrooms_text VARCHAR, 
	bedrooms VARCHAR, 
	beds VARCHAR, 
	amenities VARCHAR NOT NULL, 
	price VARCHAR, 
	minimum_nights VARCHAR NOT NULL, 
	maximum_nights VARCHAR NOT NULL, 
	minimum_minimum_nights VARCHAR NOT NULL, 
	maximum_minimum_nights VARCHAR NOT NULL, 
	minimum_maximum_nights VARCHAR NOT NULL, 
	maximum_maximum_nights VARCHAR NOT NULL, 
	minimum_nights_avg_ntm VARCHAR NOT NULL, 
	maximum_nights_avg_ntm VARCHAR NOT NULL, 
	calendar_upVARCHARd VARCHAR, 
	has_availability VARCHAR, 
	availability_30 VARCHAR NOT NULL, 
	availability_60 VARCHAR NOT NULL, 
	availability_90 VARCHAR NOT NULL, 
	availability_365 VARCHAR NOT NULL, 
	calendar_last_scraped VARCHAR NOT NULL, 
	number_of_reviews VARCHAR NOT NULL, 
	number_of_reviews_ltm VARCHAR NOT NULL, 
	number_of_reviews_l30d VARCHAR NOT NULL, 
	first_review VARCHAR, 
	last_review VARCHAR, 
	review_scores_rating VARCHAR, 
	review_scores_accuracy VARCHAR, 
	review_scores_cleanliness VARCHAR, 
	review_scores_checkin VARCHAR, 
	review_scores_communication VARCHAR, 
	review_scores_location VARCHAR, 
	review_scores_value VARCHAR, 
	license VARCHAR, 
	instant_bookable VARCHAR NOT NULL, 
	calculated_host_listings_count VARCHAR NOT NULL, 
	calculated_host_listings_count_entire_homes VARCHAR NOT NULL, 
	calculated_host_listings_count_private_rooms VARCHAR NOT NULL, 
	calculated_host_listings_count_shared_rooms VARCHAR NOT NULL, 
	reviews_per_month VARCHAR
);
