CREATE TABLE "bronze.listings" (
	id DECIMAL NOT NULL, 
	listing_url VARCHAR NOT NULL, 
	scrape_id DECIMAL NOT NULL, 
	last_scraped DATE NOT NULL, 
	source VARCHAR NOT NULL, 
	name VARCHAR NOT NULL, 
	description VARCHAR, 
	neighborhood_overview VARCHAR, 
	picture_url VARCHAR NOT NULL, 
	host_id DECIMAL NOT NULL, 
	host_url VARCHAR NOT NULL, 
	host_name VARCHAR, 
	host_since DATE, 
	host_location VARCHAR, 
	host_about VARCHAR, 
	host_response_time VARCHAR, 
	host_response_rate DECIMAL, 
	host_acceptance_rate DECIMAL, 
	host_is_superhost BOOLEAN, 
	host_thumbnail_url VARCHAR, 
	host_picture_url VARCHAR, 
	host_neighbourhood VARCHAR, 
	host_listings_count DECIMAL, 
	host_total_listings_count DECIMAL, 
	host_verifications VARCHAR, 
	host_has_profile_pic BOOLEAN, 
	host_identity_verified BOOLEAN, 
	neighbourhood VARCHAR, 
	neighbourhood_cleansed VARCHAR NOT NULL, 
	neighbourhood_group_cleansed VARCHAR NOT NULL, 
	latitude DECIMAL NOT NULL, 
	longitude DECIMAL NOT NULL, 
	property_type VARCHAR NOT NULL, 
	room_type VARCHAR NOT NULL, 
	accommodates DECIMAL NOT NULL, 
	bathrooms DECIMAL, 
	bathrooms_text VARCHAR, 
	bedrooms DECIMAL, 
	beds DECIMAL, 
	amenities VARCHAR NOT NULL, 
	price DECIMAL, 
	minimum_nights DECIMAL NOT NULL, 
	maximum_nights DECIMAL NOT NULL, 
	minimum_minimum_nights DECIMAL NOT NULL, 
	maximum_minimum_nights DECIMAL NOT NULL, 
	minimum_maximum_nights DECIMAL NOT NULL, 
	maximum_maximum_nights DECIMAL NOT NULL, 
	minimum_nights_avg_ntm DECIMAL NOT NULL, 
	maximum_nights_avg_ntm DECIMAL NOT NULL, 
	calendar_updated BOOLEAN, 
	has_availability BOOLEAN, 
	availability_30 DECIMAL NOT NULL, 
	availability_60 DECIMAL NOT NULL, 
	availability_90 DECIMAL NOT NULL, 
	availability_365 DECIMAL NOT NULL, 
	calendar_last_scraped DATE NOT NULL, 
	number_of_reviews DECIMAL NOT NULL, 
	number_of_reviews_ltm DECIMAL NOT NULL, 
	number_of_reviews_l30d DECIMAL NOT NULL, 
	first_review DATE, 
	last_review DATE, 
	review_scores_rating DECIMAL, 
	review_scores_accuracy DECIMAL, 
	review_scores_cleanliness DECIMAL, 
	review_scores_checkin DECIMAL, 
	review_scores_communication DECIMAL, 
	review_scores_location DECIMAL, 
	review_scores_value DECIMAL, 
	license VARCHAR, 
	instant_bookable BOOLEAN NOT NULL, 
	calculated_host_listings_count DECIMAL NOT NULL, 
	calculated_host_listings_count_entire_homes DECIMAL NOT NULL, 
	calculated_host_listings_count_private_rooms DECIMAL NOT NULL, 
	calculated_host_listings_count_shared_rooms DECIMAL NOT NULL, 
	reviews_per_month DECIMAL
);
